name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: make clean && make test

      - name: Generate Version
        run: echo "0.0+${{github.ref_name}}-$(git rev-parse --short HEAD)" > .version

      - name: Build
        run: make
        
      - name: Publish binaries
        uses: actions/upload-artifact@v2
        with:
          name: khosef
          path: build/
